title: "Hung NGUYEN"
#description: "CIFRE PhD Student | IP Paris × Nokia Bell Labs | Knowledge Graphs, LLMs, and Reliable AI"
theme: jekyll-theme-minimal
logo: /assets/profile.jpg  # optional (add your photo here)
show_downloads: false
github:
  is_project_page: false
social_links:
#  linkedin: "https://www.linkedin.com/in/hungnguyen-ds/"
  github: "https://github.com/HungNguyenPSL"
